#!/usr/bin/env python3
"""Builds fig_ollama.tex (Ollama vs Sushila.cpp, tokens/s, one A100) from the pod results.

Rows 1-3: same GGUF file (Ollama's own blob), decode speed: Ollama vs Sushila.cpp (our llama.cpp + 1B draft, best draft
length). Row 4: Llama-3.3-70B, speed including prompt processing: Ollama (Q4_K_M) vs Sushila.cpp serving path
(SGLang AWQ + precomputed draft head). Also prints a LaTeX table body.
Usage: python3 make_fig_ollama.py <results dir with out/ and out/compare/>
"""
import json
import os
import sys

R = sys.argv[1]
ld = lambda f: json.load(open(f'{R}/out/{f}'))
dec = lambda r: sum(x['tokens'] for x in r) / sum(x['decode_seconds'] for x in r)
wall = lambda r: sum(x['tokens'] for x in r) / sum(x['seconds'] for x in r)
rows = []
for m, name in [('llama3_2_3b', 'Llama-3.2-3B'), ('llama3_1_8b', 'Llama-3.1-8B'), ('llama3_1_70b', 'Llama-3.1-70B')]:
    o = dec(ld(f'compare/ollama_{m}.json'))
    st = dec(ld(f'compare/stock_{m}.json'))
    # Sushila.cpp uses the portfolio's choice for the model: the 1B draft only where it is faster than plain decoding
    opts = [('plain decoding', st)] + [(f'1B draft, {dm} tokens', dec(ld(f'compare/sushila_{m}_dm{dm}.json'))) for dm in (8, 16)]
    best = max(opts, key=lambda x: x[1])
    rows.append((name + ', Q4\\_K\\_M', o, st, best[1], best[0]))
o70 = f'{R}/out/compare/ollama_llama3_3_70b.json'  # our run: re-timed with 16 threads; out/ollama.json had 252
o = wall(json.load(open(o70)) if os.path.exists(o70) else ld('ollama.json'))
rows.append(('Llama-3.3-70B, 4-bit', o, None, wall(ld('dz_ck01_s4n16.json')), 'SGLang + precomputed draft head'))
# more models from the per-model pipeline (scripts/precompute): unseen prompts, Ollama vs Sushila.cpp's serving path
# PIPE_DIRS: folders holding <model>/summary.json (QWEN_DIR kept for the earlier command)
DIRS = [d for d in (os.environ.get('PIPE_DIRS', '') + ':' + os.environ.get('QWEN_DIR', '')).split(':') if d]
# Llama-3.3-70B on the unseen sets: the 7 Oct 2026 rerun through the per-model pipeline if present, else the first run
f70 = next((f'{d}/llama3.3-70b/summary.json' for d in DIRS if os.path.exists(f'{d}/llama3.3-70b/summary.json')), None)
if f70:
    t = json.load(open(f70))['sets']['ood']['tok_s']
    rows.append(('Llama-3.3-70B, unseen sets', t['ollama'], None, t['ours'], 'MT-Bench, HumanEval, GSM8K (rerun)'))
else:
    oo, dz = ld('rigor/ollama_ood.json'), ld('rigor/dz_ood.json')
    rows.append(('Llama-3.3-70B, unseen sets', wall(oo), None, wall(dz), 'MT-Bench, HumanEval, GSM8K'))
for m, name in [('qwen3-32b', 'Qwen3-32B, unseen sets'), ('qwen3-30b-a3b', 'Qwen3-30B-A3B, unseen sets'),
                ('deepseek-r1-distill-llama-70b', 'R1-Distill-Llama-70B, unseen sets'), ('gemma3-27b', 'Gemma 3 27B, unseen sets'), ('qwen3-coder-30b-a3b', 'Qwen3-Coder-30B-A3B, unseen sets'),
                ('kimi-dev-72b', 'Kimi-Dev-72B, unseen sets'), ('llama3.1-8b', 'Llama-3.1-8B (16-bit), unseen sets')]:
    f = next((f'{d}/{m}/summary.json' for d in DIRS if os.path.exists(f'{d}/{m}/summary.json')), None)
    if f:
        t = json.load(open(f))['sets']['ood']['tok_s']
        rows.append((name, t['ollama'], None, t['ours'], 'SGLang + precomputed draft head'))
for r in rows:
    print(f'{r[0]} & {r[1]:.1f} & {"" if r[2] is None else f"{r[2]:.1f}"} & {r[3]:.1f} & \\textbf{{{r[3] / r[1]:.2f}$\\times$}} & {r[4]} \\\\')
names = [r[0].replace(', Q4\\_K\\_M', '').replace(', 4-bit', '').replace(', unseen sets', '$^{*\\dagger}$') + ('$^*$' if r[2] is None and 'unseen' not in r[0] else '') for r in rows]
ylabels = ','.join('{' + n + '}' for n in names)
co = ' '.join(f'({r[1]:.1f},{i})' for i, r in enumerate(rows))
cs = ' '.join(f'({r[3]:.1f},{i})' for i, r in enumerate(rows))
cx = ' '.join(f'({r[3] / r[1]:.2f},{i})' for i, r in enumerate(rows))
xmax = max(r[3] for r in rows) * 1.22
smax = max(r[3] / r[1] for r in rows) * 1.3
common = (r'height=@HEIGHT@cm, enlarge y limits=0.16, ytick=data, y dir=reverse, xmin=0, xmajorgrids, grid style={gray!25}, '
          r'tick label style={font=\footnotesize}, label style={font=\footnotesize}, nodes near coords, '
          r'nodes near coords style={font=\scriptsize, anchor=west}, point meta=x').replace('@HEIGHT@', f'{0.76 * len(rows):.1f}')
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fig_ollama.tex'), 'w').write(rf"""\documentclass[border=4pt]{{standalone}}
\usepackage[T1]{{fontenc}}
\usepackage{{lmodern}}
\usepackage{{pgfplots}}
\pgfplotsset{{compat=1.17}}
\begin{{document}}
% Generated by make_fig_ollama.py from the pod results; do not edit by hand.
\begin{{tikzpicture}}
\begin{{axis}}[name=speed, xbar, width=9.2cm, bar width=7pt, {common}, xmax={xmax:.0f},
  yticklabels={{{ylabels}}}, xlabel={{Tokens per second, one A100 80GB}},
  legend style={{at={{(0.97,0.74)}}, anchor=east, font=\footnotesize, draw=gray!40}}, legend cell align=left,
  every node near coord/.append style={{/pgf/number format/fixed, /pgf/number format/precision=1}}]
\addplot[fill=gray!45, draw=gray!70] coordinates {{{co}}};
\addplot[fill=teal!70, draw=teal!90!black] coordinates {{{cs}}};
\legend{{Ollama (stock), Sushila.cpp}}
\end{{axis}}
\begin{{axis}}[at={{(speed.east)}}, anchor=west, xshift=0.6cm, xbar, width=5.4cm, bar width=9pt, {common}, xmax={smax:.1f},
  yticklabels={{}}, xlabel={{Speedup over Ollama}},
  every node near coord/.append style={{/pgf/number format/fixed, /pgf/number format/fixed zerofill, /pgf/number format/precision=2}},
  nodes near coords={{\pgfmathprintnumber{{\pgfplotspointmeta}}$\times$}}]
\addplot[fill=teal!70, draw=teal!90!black] coordinates {{{cx}}};
\draw[gray!70, dashed] (axis cs:1,-0.5) -- (axis cs:1,{len(rows) - 0.5});
\end{{axis}}
\end{{tikzpicture}}
\end{{document}}
""")
print('wrote fig_ollama.tex')
