#!/usr/bin/env python3
"""Copies the documentation page (cli/web/sushila_docs.html, the one `sushila serve` shows at /docs) into the website
worker (between the SUSHILA_DOCS markers), so sushila.ai/docs and the local /docs are the same file.
  python3 scripts/website/embed_docs.py [worker.js ...]"""
import sys, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
html = (root / 'cli/web/sushila_docs.html').read_text()
html = html.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')  # it sits in a JS template literal
for w in sys.argv[1:] or [str(root / 'website/worker.js')]:
    s = pathlib.Path(w).read_text()
    a, b = s.index('// SUSHILA_DOCS_BEGIN'), s.index('// SUSHILA_DOCS_END')
    s = s[:a] + '// SUSHILA_DOCS_BEGIN (generated by scripts/website/embed_docs.py from cli/web/sushila_docs.html: edit that file)\nconst SUSHILA_DOCS_HTML = `' + html + '`;\n' + s[b:]
    pathlib.Path(w).write_text(s); print('docs embedded in', w)
