// The Library: everything made with Sushila on this computer, in one list. Files live in the home folder:
//   outputs/images/<date>/  pictures from the Inference page      outputs/music/<date>/  songs     outputs/video/<date>/  videos
//   outputs/<job>.<ext>     results of queue jobs
// and outputs/library.jsonl keeps one line per file with what made it (prompt, lyrics, model, mode, size, seed, time),
// so the Library tab can search every field. Files on disk without a line (older ones) are listed too.
use serde_json::{json, Value};
use std::path::{Path, PathBuf};

const EXTS: [(&str, &str); 11] = [("png", "image"), ("jpg", "image"), ("jpeg", "image"), ("webp", "image"), ("gif", "image"),
    ("mp3", "music"), ("wav", "music"), ("flac", "music"), ("ogg", "music"), ("webm", "video"), ("mp4", "video")];
pub fn kind_of(p: &Path) -> Option<&'static str> {
    let e = p.extension()?.to_string_lossy().to_lowercase();
    EXTS.iter().find(|(x, _)| *x == e).map(|(_, k)| *k)
}
pub fn mime_of(p: &Path) -> &'static str {
    match p.extension().map(|e| e.to_string_lossy().to_lowercase()).as_deref() {
        Some("png") => "image/png", Some("jpg") | Some("jpeg") => "image/jpeg", Some("webp") => "image/webp", Some("gif") => "image/gif",
        Some("mp3") => "audio/mpeg", Some("wav") => "audio/wav", Some("flac") => "audio/flac", Some("ogg") => "audio/ogg",
        Some("webm") => "video/webm", Some("mp4") => "video/mp4", _ => "application/octet-stream",
    }
}

/// Words of a prompt for a file name: "a red fox in the snow" -> "a-red-fox-in-the-snow".
pub fn slug(text: &str) -> String {
    let s: String = text.split("<sd_cpp_extra_args>").next().unwrap_or("").split(|c: char| !c.is_alphanumeric()).filter(|w| !w.is_empty())
        .take(6).collect::<Vec<_>>().join("-").to_lowercase().chars().take(48).collect();
    s.trim_matches('-').to_string()
}

/// One line in outputs/library.jsonl for a file just made (`meta`: prompt, lyrics, pack, mode, size, seed, ...).
pub fn record(dir: &Path, file: &Path, kind: &str, mut meta: Value) {
    use std::io::Write;
    let rel = file.strip_prefix(crate::locate::outputs(dir)).map(|r| r.to_string_lossy().replace('\\', "/")).unwrap_or_default();
    if rel.is_empty() { return; }
    meta["rel"] = json!(rel); meta["kind"] = json!(kind); meta["created"] = json!(crate::util::now_iso());
    if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(crate::locate::outputs(dir).join("library.jsonl")) { let _ = writeln!(f, "{meta}"); }
}

// ---------- "made by AI" in every file Sushila writes (EU AI Act art. 50(2): machine-readable marking; China's labelling
// rules: an implicit label in the metadata). The standard field is IPTC DigitalSourceType = trainedAlgorithmicMedia,
// written as XMP (pictures) or as an ID3 tag (songs); the content itself is not changed.
const DST: &str = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia";
/// Written into every file: who made it, where, and where to report misuse. Where: on the computer of the person who
/// asked (the page or app on this computer), or on a Sushila Engine for someone on another device (a remote request).
pub const MAKE_YOUR_OWN: &str = "You too can create unlimited free pictures, music and videos on your PC or laptop with sushila.cpp, downloadable at https://sushila.ai/install";
pub fn disclaimer(remote: bool) -> String {
    format!("{}. To report abuse: https://sushila.ai/reportabuse. {MAKE_YOUR_OWN}",
        if remote { "Generated on a remote Sushila Engine (sushila.cpp), at the request of a user on another device" } else { "Generated by a user with sushila.cpp on their local machine" })
}
fn crc32(data: &[u8]) -> u32 {
    let mut c = 0xFFFF_FFFFu32;
    for &b in data { c ^= b as u32; for _ in 0..8 { c = if c & 1 != 0 { 0xEDB8_8320 ^ (c >> 1) } else { c >> 1 }; } }
    !c
}
fn esc(t: &str) -> String { t.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;").replace('"', "&quot;") }
/// The bytes with the AI marking added (PNG: an XMP iTXt chunk and tEXt fields before IEND; MP3: an ID3v2.3 tag in front,
/// unless the file has one already; WebM: a Tags element at the end, listed in the SeekHead). Other formats come back unchanged.
pub fn mark_ai(bytes: &[u8], ext: &str, pack: &str, prompt: &str, remote: bool) -> Vec<u8> {
    let disc = disclaimer(remote);
    let generated = if remote { "remote Sushila Engine" } else { "local machine" };
    let tool = format!("Sushila {} (model: {})", env!("CARGO_PKG_VERSION"), if pack.is_empty() { "unknown" } else { pack });
    let note = format!("AI-generated with {tool}. {disc}. Prompt: {}", prompt.chars().take(500).collect::<String>());
    let now = crate::util::now_iso();
    match ext {
        "png" if bytes.len() >= 20 && bytes[..8] == [0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A] && bytes[bytes.len() - 8..bytes.len() - 4] == *b"IEND" => {
            let chunk = |typ: &[u8], data: &[u8]| -> Vec<u8> {
                let mut c = (data.len() as u32).to_be_bytes().to_vec(); let mut td = typ.to_vec(); td.extend_from_slice(data);
                c.extend_from_slice(&td); c.extend_from_slice(&crc32(&td).to_be_bytes()); c
            };
            let xmp = format!("<x:xmpmeta xmlns:x=\"adobe:ns:meta/\"><rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"><rdf:Description rdf:about=\"\" \
xmlns:Iptc4xmpExt=\"http://iptc.org/std/Iptc4xmpExt/2008-02-29/\" xmlns:xmp=\"http://ns.adobe.com/xap/1.0/\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" \
Iptc4xmpExt:DigitalSourceType=\"{DST}\" xmp:CreatorTool=\"{}\" xmp:CreateDate=\"{now}\"><dc:description><rdf:Alt><rdf:li xml:lang=\"x-default\">{}</rdf:li></rdf:Alt></dc:description>\
</rdf:Description></rdf:RDF></x:xmpmeta>", esc(&tool), esc(&note));
            let mut itxt = b"XML:com.adobe.xmp\0\0\0\0\0".to_vec(); itxt.extend_from_slice(xmp.as_bytes());
            let mut out = bytes[..bytes.len() - 12].to_vec();
            out.extend(chunk(b"iTXt", &itxt));
            for (k, v) in [("Software", tool.as_str()), ("Comment", note.as_str()), ("Disclaimer", disc.as_str()), ("Generated-On", generated), ("AI-Generated", "true"), ("DigitalSourceType", DST)] {
                let mut d = k.as_bytes().to_vec(); d.push(0); d.extend(v.chars().filter(|c| (*c as u32) < 256).map(|c| c as u8)); out.extend(chunk(b"tEXt", &d));
            }
            out.extend_from_slice(&bytes[bytes.len() - 12..]);
            out
        }
        "mp3" if !bytes.starts_with(b"ID3") => {
            let latin = |t: &str| -> Vec<u8> { t.chars().map(|c| if (c as u32) < 256 { c as u8 } else { b'?' }).collect() };
            let frame = |id: &[u8], data: Vec<u8>| -> Vec<u8> { let mut f = id.to_vec(); f.extend_from_slice(&(data.len() as u32).to_be_bytes()); f.extend_from_slice(&[0, 0]); f.extend(data); f };
            let txxx = |desc: &str, val: &str| -> Vec<u8> { let mut d = vec![0u8]; d.extend(latin(desc)); d.push(0); d.extend(latin(val)); frame(b"TXXX", d) };
            let mut body = vec![];
            body.extend(frame(b"TSSE", { let mut d = vec![0u8]; d.extend(latin(&tool)); d }));
            body.extend(frame(b"COMM", { let mut d = vec![0u8]; d.extend_from_slice(b"eng"); d.push(0); d.extend(latin(&note)); d }));
            body.extend(frame(b"TIT2", { let mut d = vec![0u8]; d.extend(latin(&prompt.chars().take(120).collect::<String>())); d }));
            body.extend(txxx("AI_GENERATED", "true"));
            body.extend(txxx("DIGITAL_SOURCE_TYPE", DST));
            body.extend(txxx("DISCLAIMER", &disc));
            body.extend(txxx("GENERATED_ON", generated));
            body.extend(txxx("CREATED", &now));
            let n = body.len() as u32;
            let mut out = b"ID3\x03\x00\x00".to_vec();
            out.extend_from_slice(&[((n >> 21) & 0x7f) as u8, ((n >> 14) & 0x7f) as u8, ((n >> 7) & 0x7f) as u8, (n & 0x7f) as u8]);  // synchsafe size
            out.extend(body); out.extend_from_slice(bytes);
            out
        }
        "webm" | "mkv" => webm_tags(bytes, &[("AI_GENERATED", "true"), ("DIGITAL_SOURCE_TYPE", DST), ("ENCODER", &tool), ("COMMENT", &note),
            ("DISCLAIMER", &disc), ("GENERATED_ON", generated), ("DATE_RELEASED", &now)]).unwrap_or_else(|| bytes.to_vec()),
        _ => bytes.to_vec(),
    }
}

// ---------- WebM / Matroska: EBML elements are ID + size (a variable-length number) + data. A second Tags element is
// appended at the end of the Segment (Matroska allows several), so nothing before it moves: the clusters and the Cues keep
// their positions. The Segment size grows by the new element, and a Seek entry pointing to it goes into the Void that
// muxers leave after the SeekHead, so players that read tags through the SeekHead find it too.
fn vint(b: &[u8], p: usize) -> Option<(u64, usize)> {  // (value, width) of the size at p
    let first = *b.get(p)?; let w = first.leading_zeros() as usize + 1;
    if w > 8 || p + w > b.len() { return None; }
    let mut v = (first as u64) & (0xFFu64 >> w);
    for i in 1..w { v = (v << 8) | b[p + i] as u64; }
    Some((v, w))
}
#[cfg(test)]
fn id_len(b: &[u8], p: usize) -> Option<usize> { let w = b.get(p)?.leading_zeros() as usize + 1; if w > 4 { None } else { Some(w) } }
fn vint_bytes(v: u64, w: usize) -> Option<Vec<u8>> {  // v as a size of exactly w bytes
    if w == 0 || w > 8 || v >= (1u64 << (7 * w)) - 1 { return None; }
    let x = v | (1u64 << (7 * w));
    Some((0..w).rev().map(|i| (x >> (8 * i)) as u8).collect())
}
fn el(id: &[u8], data: &[u8]) -> Vec<u8> {
    let w = (1..=8).find(|&w| (data.len() as u64) < (1u64 << (7 * w)) - 1).unwrap_or(8);
    [id, &vint_bytes(data.len() as u64, w).unwrap_or_default()[..], data].concat()
}
fn webm_tags(b: &[u8], tags: &[(&str, &str)]) -> Option<Vec<u8>> {
    // EBML header, then the Segment
    if !b.starts_with(&[0x1A, 0x45, 0xDF, 0xA3]) { return None; }
    // every size read from the file is checked against the file's length (a damaged file is left as it is)
    let (hl, hw) = vint(b, 4)?;
    let mut p = 4usize.checked_add(hw)?.checked_add(usize::try_from(hl).ok()?)?;
    if b.get(p..p.checked_add(4)?)? != [0x18, 0x53, 0x80, 0x67] { return None; }
    let (seg_len, seg_w) = vint(b, p + 4)?;
    let seg_size_at = p + 4; let seg_data = p + 4 + seg_w;
    if (seg_data as u64).checked_add(seg_len)? != b.len() as u64 { return None; }  // unknown size or something after the Segment: leave it
    let simple: Vec<u8> = tags.iter().flat_map(|(k, v)| el(&[0x67, 0xC8], &[el(&[0x45, 0xA3], k.as_bytes()), el(&[0x44, 0x87], v.as_bytes())].concat())).collect();
    let new_tags = el(&[0x12, 0x54, 0xC3, 0x67], &el(&[0x73, 0x73], &[el(&[0x63, 0xC0], &[]), simple].concat()));
    let tags_pos = (b.len() - seg_data) as u64;  // position inside the Segment
    let mut out = b.to_vec();
    out.splice(seg_size_at..seg_data, vint_bytes(seg_len + new_tags.len() as u64, seg_w)?);
    // the SeekHead (first child) and the Void right after it
    p = seg_data;
    if out.get(p..p + 4) == Some(&[0x11, 0x4D, 0x9B, 0x74]) {
        let (sh_len, sh_w) = vint(&out, p + 4)?;
        let void_at = (p + 4 + sh_w).checked_add(usize::try_from(sh_len).ok()?)?;
        if out.get(void_at) == Some(&0xEC) {
            let (v_len, v_w) = vint(&out, void_at + 1)?;
            let void_total = (1 + v_w).checked_add(usize::try_from(v_len).ok()?)?;
            if void_at.checked_add(void_total)? > out.len() { return None; }
            let pos: Vec<u8> = { let bs = tags_pos.to_be_bytes(); let z = bs.iter().position(|&x| x != 0).unwrap_or(7); bs[z..].to_vec() };
            let seek = el(&[0x4D, 0xBB], &[el(&[0x53, 0xAB], &[0x12, 0x54, 0xC3, 0x67]), el(&[0x53, 0xAC], &pos)].concat());
            let rest = void_total.checked_sub(seek.len()).unwrap_or(0);
            if let (Some(sz), true) = (vint_bytes(sh_len + seek.len() as u64, sh_w), rest >= 2) {
                let vw = if rest - 2 < 127 { 1 } else { 8.min(rest - 1) };
                if let Some(vs) = vint_bytes((rest - 1 - vw) as u64, vw) {
                    let mut void = vec![0xEC]; void.extend(vs); void.resize(rest, 0);
                    out.splice(void_at..void_at + void_total, [seek, void].concat());
                    out.splice(p + 4..p + 4 + sh_w, sz);
                }
            }
        }
    }
    out.extend(new_tags);
    Some(out)
}

/// The folder for a kind of file: Images, Music, Videos (the lower-case images, music, video of a files folder from
/// before build 27 are kept where they exist, so one folder never gets two).
pub fn kind_folder(out: &Path, kind: &str) -> &'static str {
    let (old, new) = match kind { "image" => ("images", "Images"), "video" => ("video", "Videos"), _ => ("music", "Music") };
    if out.join(old).is_dir() { old } else { new }
}
/// Writes a result to outputs/<kind folder>/<date>/<HHMMSS>-<words>.<ext>, records it, returns its path.
pub fn save(dir: &Path, kind: &str, ext: &str, bytes: &[u8], title: &str, meta: Value) -> Option<PathBuf> {
    let now = crate::util::now_iso();
    let out = crate::locate::outputs(dir);
    let day = out.join(kind_folder(&out, kind)).join(&now[..10]);
    std::fs::create_dir_all(&day).ok()?;
    let stamp: String = now[11..19].chars().filter(|c| c.is_ascii_digit()).collect();
    let base = format!("{stamp}-{}", { let s = slug(title); if s.is_empty() { kind.to_string() } else { s } });
    let mut f = day.join(format!("{base}.{ext}"));
    let mut k = 2; while f.exists() { f = day.join(format!("{base}-{k}.{ext}")); k += 1; }
    let marked = mark_ai(bytes, ext, meta["pack"].as_str().unwrap_or(""), meta["prompt"].as_str().unwrap_or(title), meta["remote"] == true);
    std::fs::write(&f, marked).ok()?;
    record(dir, &f, kind, meta);
    Some(f)
}

/// The first audio part of a multipart answer (the music engine sends the song with its metadata).
pub fn audio_in_multipart(body: &[u8], ctype: &str) -> Option<(Vec<u8>, String)> {
    let b = ctype.split(';').map(str::trim).find_map(|p| p.strip_prefix("boundary="))?.trim_matches('"').to_string();
    let sep = format!("--{b}");
    let text = body;
    let find = |hay: &[u8], needle: &[u8], from: usize| hay.get(from..)?.windows(needle.len()).position(|w| w == needle).map(|i| i + from);
    let mut at = find(text, sep.as_bytes(), 0)?;
    loop {
        let start = at + sep.len();
        if text.get(start..start + 2) == Some(b"--") { return None; }
        let next = find(text, sep.as_bytes(), start)?;
        // the part's headers end before the next boundary; a part without them is skipped
        let Some(head_end) = find(&text[..next], b"\r\n\r\n", start) else { at = next; continue };
        let head = String::from_utf8_lossy(&text[start..head_end]).to_lowercase();
        if let Some(t) = head.lines().find_map(|l| l.strip_prefix("content-type:")).map(|t| t.trim().to_string()).filter(|t| t.starts_with("audio/")) {
            let mut end = next; if end >= 2 && text.get(end - 2..end) == Some(b"\r\n") { end -= 2; }
            return (head_end + 4 <= end).then(|| (text[head_end + 4..end].to_vec(), t));
        }
        at = next;
    }
}

/// Everything in outputs/, newest first: the files on disk, with what the index and the queue know about each.
pub fn list(dir: &Path) -> Vec<Value> {
    let out = crate::locate::outputs(dir);
    let mut meta: std::collections::HashMap<String, Value> = std::collections::HashMap::new();
    for l in std::fs::read_to_string(out.join("library.jsonl")).unwrap_or_default().lines() {
        if let Ok(v) = serde_json::from_str::<Value>(l) { if let Some(r) = v["rel"].as_str() { meta.insert(r.to_string(), v); } }
    }
    // queue jobs: their output file and what they were asked
    let q = crate::webserver::read_queue(dir);
    for j in q["jobs"].as_array().cloned().unwrap_or_default() {
        if let Some(f) = j["output"]["file"].as_str() {
            meta.entry(f.to_string()).or_insert_with(|| json!({ "pack": j["model"], "prompt": j["params"]["prompt"].as_str().or(j["params"]["style"].as_str()).or(j["title"].as_str()),
                "lyrics": j["params"]["lyrics"], "seed": j["params"]["seed"], "size": j["params"]["size"], "duration": j["params"]["duration"], "source": "queue", "created": j["created"] }));
        }
    }
    let mut items = vec![];
    let mut stack = vec![out.clone()];
    while let Some(d) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&d) else { continue };
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() { if !p.file_name().map(|n| n.to_string_lossy().starts_with('.')).unwrap_or(false) { stack.push(p); } continue; }
            let Some(kind) = kind_of(&p) else { continue };
            let md = e.metadata().ok();
            let rel = p.strip_prefix(&out).map(|r| r.to_string_lossy().replace('\\', "/")).unwrap_or_default();
            let m = meta.get(&rel).cloned().unwrap_or(json!({}));
            let modified = md.as_ref().and_then(|m| m.modified().ok()).map(iso).unwrap_or_default();
            let mut v = json!({ "rel": rel, "path": p.to_string_lossy(), "name": p.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
                "kind": m["kind"].as_str().unwrap_or(kind), "bytes": md.map(|m| m.len()).unwrap_or(0), "created": m["created"].as_str().map(String::from).unwrap_or(modified) });
            for k in ["pack", "mode", "prompt", "lyrics", "seed", "size", "duration", "frames", "source"] { if !m[k].is_null() { v[k] = m[k].clone(); } }
            items.push(v);
        }
    }
    items.sort_by(|a, b| b["created"].as_str().cmp(&a["created"].as_str()));
    items
}
// ---------- moving your files to another folder (the one question after build 27, and Settings -> Where my files go)

/// Moves everything in one files folder into another: pictures, songs, videos, queue results, the index, the shared
/// links and the trash. Renamed where it can be (instant on one drive), else copied and then removed. The old
/// images/, music/, video/ become Images/, Music/, Videos/, and the index lines follow; a name already taken in the
/// new folder gets -2, -3, ...; the index files are joined. Returns how many files moved.
/// "images/x/y.png" -> "Images/x/y.png" (and music/ -> Music/, video/ -> Videos/); None for any other path.
fn new_top(rel: &str) -> Option<String> {
    let top = rel.split('/').next().unwrap_or("");
    let nt = match top { "images" => "Images", "music" => "Music", "video" => "Videos", _ => return None };
    Some(format!("{nt}{}", &rel[top.len()..]))
}
pub fn move_files(from: &Path, to: &Path) -> Result<usize, String> {
    use std::collections::HashMap;
    let canon = |p: &Path| std::fs::canonicalize(p).unwrap_or_else(|_| p.to_path_buf());
    if !from.is_dir() { return Ok(0); }
    std::fs::create_dir_all(to).map_err(|e| format!("cannot make {}: {e}", to.display()))?;
    let (f, t) = (canon(from), canon(to));
    if f == t { return Ok(0); }
    if t.starts_with(&f) || f.starts_with(&t) { return Err("the two folders are inside each other; choose a folder outside".into()); }
    let mut renamed: HashMap<String, String> = HashMap::new();
    let mut n = 0usize;
    fn count(p: &Path) -> usize { if p.is_dir() { std::fs::read_dir(p).map(|d| d.flatten().map(|e| count(&e.path())).sum()).unwrap_or(0) } else { 1 } }
    fn go(src: &Path, dst: &Path, rel_old: &str, rel_new: &str, renamed: &mut HashMap<String, String>, n: &mut usize) -> Result<(), String> {
        let name = |p: &Path| p.file_name().map(|x| x.to_string_lossy().to_string()).unwrap_or_default();
        if src.is_dir() {
            if !dst.exists() {
                let c = count(src);
                if std::fs::rename(src, dst).is_ok() { *n += c; if rel_old != rel_new { renamed.insert(format!("{rel_old}/"), format!("{rel_new}/")); } return Ok(()); }
            }
            std::fs::create_dir_all(dst).map_err(|e| format!("cannot make {}: {e}", dst.display()))?;
            for e in std::fs::read_dir(src).map_err(|e| e.to_string())?.flatten() {
                let k = name(&e.path());
                go(&e.path(), &dst.join(&k), &format!("{rel_old}/{k}"), &format!("{rel_new}/{k}"), renamed, n)?;
            }
            let _ = std::fs::remove_dir(src);
            return Ok(());
        }
        let mut dst = dst.to_path_buf();
        if dst.exists() {
            if name(src).ends_with(".jsonl") {
                // index files: the old lines go after the new ones
                use std::io::Write;
                let text = std::fs::read(src).map_err(|e| e.to_string())?;
                let mut o = std::fs::OpenOptions::new().append(true).open(&dst).map_err(|e| e.to_string())?;
                o.write_all(&text).map_err(|e| e.to_string())?;
                let _ = std::fs::remove_file(src); *n += 1; return Ok(());
            }
            let (stem, ext) = (dst.file_stem().map(|x| x.to_string_lossy().to_string()).unwrap_or_default(), dst.extension().map(|x| format!(".{}", x.to_string_lossy())).unwrap_or_default());
            let mut k = 2; while dst.exists() { dst = dst.with_file_name(format!("{stem}-{k}{ext}")); k += 1; }
            let new_rel = format!("{}/{}", rel_new.rsplit_once('/').map(|x| x.0).unwrap_or(""), name(&dst));
            renamed.insert(rel_old.to_string(), new_rel);
        } else if rel_old != rel_new { renamed.insert(rel_old.to_string(), rel_new.to_string()); }
        if std::fs::rename(src, &dst).is_err() {
            std::fs::copy(src, &dst).map_err(|e| format!("cannot write {}: {e}", dst.display()))?;
            std::fs::remove_file(src).map_err(|e| format!("copied, but cannot remove {}: {e}", src.display()))?;
        }
        *n += 1;
        Ok(())
    }
    for e in std::fs::read_dir(from).map_err(|e| e.to_string())?.flatten() {
        let k = e.file_name().to_string_lossy().to_string();
        let nk = match k.as_str() { "images" => "Images", "music" => "Music", "video" => "Videos", x => x }.to_string();
        // on Windows and macOS "images" and "Images" are one name: the rename above already gives the new spelling
        go(&e.path(), &to.join(&nk), &k, &nk, &mut renamed, &mut n)?;
    }
    let _ = std::fs::remove_dir(from);
    // the index lines (library, shared links, trash) name files by their path in the folder: follow the moves
    let fix = |r: &str| -> Option<String> {
        if let Some(x) = renamed.get(r) { return Some(x.trim_start_matches('/').to_string()); }
        new_top(r)
    };
    // (the trash keeps its own layout; restore() puts a file from an old images/ back into Images/)
    for idx in [to.join("library.jsonl"), to.join("shared.jsonl")] {
        let Ok(text) = std::fs::read_to_string(&idx) else { continue };
        let lines: Vec<String> = text.lines().map(|l| match serde_json::from_str::<Value>(l) {
            Ok(mut v) => { if let Some(nr) = v["rel"].as_str().and_then(&fix) { v["rel"] = json!(nr); } v.to_string() }
            Err(_) => l.to_string(),
        }).collect();
        let _ = std::fs::write(&idx, lines.join("\n") + "\n");
    }
    Ok(n)
}

// ---------- the trash: Delete moves a file to outputs/.trash/<same place>; Restore moves it back; Delete permanently
// removes it. outputs/.trash/trash.jsonl keeps when each was deleted (and its index line, so a restored file keeps
// its prompt and model).
fn trash(dir: &Path) -> PathBuf { crate::locate::outputs(dir).join(".trash") }
/// A path given by the page, made safe: relative, inside outputs (or the trash), no "..".
fn safe(base: &Path, rel: &str) -> Option<PathBuf> {
    if rel.is_empty() || rel.starts_with('/') || rel.starts_with('\\') || rel.contains(':') || rel.split(['/', '\\']).any(|c| c == ".." || c == "." || c.is_empty()) { return None; }
    Some(base.join(rel))
}
/// An existing file under `base` named by a Library path: the path rules above, then the real location (links
/// resolved) must still be inside `base`. None for anything else (absolute, UNC, drive letters, "..", links out).
pub fn resolve(base: &Path, rel: &str) -> Option<PathBuf> {
    let p = std::fs::canonicalize(safe(base, rel)?).ok()?;
    let b = std::fs::canonicalize(base).ok()?;
    (p.starts_with(&b) && p.is_file()).then_some(p)
}
pub fn delete(dir: &Path, rel: &str) -> Result<(), String> {
    use std::io::Write;
    if rel.starts_with(".trash") { return Err("already in the trash".into()); }
    let from = safe(&crate::locate::outputs(dir), rel).filter(|p| p.is_file()).ok_or("no such file")?;
    let to = trash(dir).join(rel);
    if let Some(d) = to.parent() { std::fs::create_dir_all(d).map_err(|e| e.to_string())?; }
    std::fs::rename(&from, &to).map_err(|e| e.to_string())?;
    let meta = list_meta(dir).remove(rel).unwrap_or(json!({}));
    if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(trash(dir).join("trash.jsonl")) {
        let _ = writeln!(f, "{}", json!({ "rel": rel, "deleted": crate::util::now_iso(), "meta": meta }));
    }
    Ok(())
}
pub fn restore(dir: &Path, rel: &str) -> Result<(), String> {
    let from = safe(&trash(dir), rel).filter(|p| p.is_file()).ok_or("not in the trash")?;
    let out = crate::locate::outputs(dir);
    // a file deleted before its folder moved to the new names goes back under the new name (Images/, not images/)
    let rel = new_top(rel).filter(|n| !out.join(rel.split('/').next().unwrap_or("")).is_dir() && out.join(n.split('/').next().unwrap_or("")).is_dir()).unwrap_or(rel.to_string());
    let to = out.join(&rel);
    if to.exists() { return Err("a file with that name is back already".into()); }
    if let Some(d) = to.parent() { std::fs::create_dir_all(d).map_err(|e| e.to_string())?; }
    std::fs::rename(&from, &to).map_err(|e| e.to_string())
}
pub fn purge(dir: &Path, rel: &str) -> Result<(), String> {
    let f = safe(&trash(dir), rel).filter(|p| p.is_file()).ok_or("not in the trash")?;
    std::fs::remove_file(f).map_err(|e| e.to_string())
}
/// Removes everything in the trash; returns how many files.
pub fn empty_trash(dir: &Path) -> usize {
    let n = list_trash(dir).len();
    let _ = std::fs::remove_dir_all(trash(dir));
    n
}
/// What is in the trash, newest deletion first (with the details the file had).
pub fn list_trash(dir: &Path) -> Vec<Value> {
    let t = trash(dir);
    let mut when: std::collections::HashMap<String, Value> = std::collections::HashMap::new();
    for l in std::fs::read_to_string(t.join("trash.jsonl")).unwrap_or_default().lines() {
        if let Ok(v) = serde_json::from_str::<Value>(l) { if let Some(r) = v["rel"].as_str() { when.insert(r.to_string(), v); } }
    }
    let mut items = vec![];
    let mut stack = vec![t.clone()];
    while let Some(d) = stack.pop() {
        let Ok(rd) = std::fs::read_dir(&d) else { continue };
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() { stack.push(p); continue; }
            let Some(kind) = kind_of(&p) else { continue };
            let rel = p.strip_prefix(&t).map(|r| r.to_string_lossy().replace('\\', "/")).unwrap_or_default();
            let w = when.get(&rel).cloned().unwrap_or(json!({}));
            let mut v = json!({ "rel": rel, "path": p.to_string_lossy(), "name": p.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
                "kind": kind, "bytes": e.metadata().map(|m| m.len()).unwrap_or(0), "deleted": w["deleted"], "trash": true });
            for k in ["pack", "mode", "prompt", "lyrics", "seed", "size", "duration", "created"] { if !w["meta"][k].is_null() { v[k] = w["meta"][k].clone(); } }
            items.push(v);
        }
    }
    items.sort_by(|a, b| b["deleted"].as_str().cmp(&a["deleted"].as_str()));
    items
}
fn list_meta(dir: &Path) -> std::collections::HashMap<String, Value> {
    let mut meta = std::collections::HashMap::new();
    for l in std::fs::read_to_string(crate::locate::outputs(dir).join("library.jsonl")).unwrap_or_default().lines() {
        if let Ok(v) = serde_json::from_str::<Value>(l) { if let Some(r) = v["rel"].as_str() { meta.insert(r.to_string(), v); } }
    }
    meta
}

fn iso(t: std::time::SystemTime) -> String {
    let s = t.duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs() as i64).unwrap_or(0);
    let (days, rem) = (s.div_euclid(86400), s.rem_euclid(86400));
    // civil date from days (Howard Hinnant)
    let z = days + 719468; let era = z.div_euclid(146097); let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365; let y = yoe + era * 400; let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153; let d = doy - (153 * mp + 2) / 5 + 1; let m = if mp < 10 { mp + 3 } else { mp - 9 };
    format!("{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z", if m <= 2 { y + 1 } else { y }, m, d, rem / 3600, rem % 3600 / 60, rem % 60)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test] fn saves_lists_and_reads_multipart() {
        let dir = std::env::temp_dir().join(format!("sushila-lib-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir); std::fs::create_dir_all(&dir).unwrap();
        let f = save(&dir, "music", "mp3", b"ID3fake", "Upbeat pop, female vocals", json!({ "pack": "ace-step-15", "prompt": "Upbeat pop, female vocals", "lyrics": "[Verse] hello", "duration": 60 })).unwrap();
        assert!(f.to_string_lossy().contains("outputs") && f.file_name().unwrap().to_string_lossy().ends_with("-upbeat-pop-female-vocals.mp3"));
        std::fs::write(crate::locate::outputs(&dir).join("old.png"), b"png").unwrap();  // an older file without a line in the index
        let l = list(&dir);
        assert_eq!(l.len(), 2);
        let song = l.iter().find(|x| x["kind"] == "music").unwrap();
        assert_eq!(song["pack"], "ace-step-15"); assert_eq!(song["lyrics"], "[Verse] hello"); assert_eq!(song["bytes"], 7);
        assert!(l.iter().any(|x| x["name"] == "old.png" && x["kind"] == "image" && x["created"].as_str().unwrap().len() == 20));
        let body = b"--XyZ\r\nContent-Type: application/json\r\n\r\n{}\r\n--XyZ\r\nContent-Type: audio/mpeg\r\n\r\nMP3DATA\r\n--XyZ--\r\n";
        let (a, t) = audio_in_multipart(body, "multipart/mixed; boundary=XyZ").unwrap();
        assert_eq!(a, b"MP3DATA"); assert_eq!(t, "audio/mpeg");
        // delete -> trash -> restore; delete -> purge; paths outside are refused
        let rel = song["rel"].as_str().unwrap().to_string();
        delete(&dir, &rel).unwrap();
        assert_eq!(list(&dir).len(), 1); let t = list_trash(&dir); assert_eq!(t.len(), 1); assert_eq!(t[0]["prompt"], "Upbeat pop, female vocals");
        restore(&dir, &rel).unwrap(); assert_eq!(list(&dir).len(), 2); assert!(list_trash(&dir).is_empty());
        delete(&dir, "old.png").unwrap(); purge(&dir, "old.png").unwrap(); assert_eq!(list(&dir).len(), 1); assert!(list_trash(&dir).is_empty());
        assert!(delete(&dir, "../state.json").is_err() && delete(&dir, "/etc/passwd").is_err() && restore(&dir, "a/../../x").is_err());
        delete(&dir, &rel).unwrap(); assert_eq!(empty_trash(&dir), 1); assert!(list(&dir).is_empty());
        // the AI marking: a valid PNG stays valid (CRCs), an MP3 gets an ID3 tag in front
        let png: Vec<u8> = [&[0x89u8, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A][..], &[0, 0, 0, 0], b"IEND", &crc32(b"IEND").to_be_bytes()].concat();
        let m = mark_ai(&png, "png", "z-image-turbo", "a fox", false);
        assert!(String::from_utf8_lossy(&m).contains("local machine") && String::from_utf8_lossy(&mark_ai(&png, "png", "z", "a fox", true)).contains("remote Sushila Engine"));
        assert!(m.windows(18).any(|w| w == b"XML:com.adobe.xmp\0") && m.ends_with(&png[8..]) && String::from_utf8_lossy(&m).contains("trainedAlgorithmicMedia"));
        assert_eq!(crc32(b"IEND"), 0xAE42_6082);
        let mp3 = mark_ai(b"\xff\xfbDATA", "mp3", "ace-step-15", "pop", false); assert!(mp3.starts_with(b"ID3\x03") && mp3.ends_with(b"\xff\xfbDATA") && String::from_utf8_lossy(&mp3).contains("AI_GENERATED"));
        assert_eq!(mark_ai(b"ID3old", "mp3", "", "", false), b"ID3old"); assert_eq!(mark_ai(b"webm", "webm", "", "", false), b"webm");
        // WebM: EBML header + Segment(SeekHead, Void, Cluster); the marked file keeps every byte before the end in place
        // except the sizes, and parses back to the same elements plus a Tags at the end
        let seekhead = el(&[0x11, 0x4D, 0x9B, 0x74], &el(&[0x4D, 0xBB], &[el(&[0x53, 0xAB], &[0x1F, 0x43, 0xB6, 0x75]), el(&[0x53, 0xAC], &[0x30])].concat()));
        let seg_body = [seekhead.clone(), vec![0xEC, 0x80 | 28], vec![0; 28], el(&[0x1F, 0x43, 0xB6, 0x75], b"frames")].concat();
        let mut webm = el(&[0x1A, 0x45, 0xDF, 0xA3], &el(&[0x42, 0x82], b"webm"));
        webm.extend([0x18, 0x53, 0x80, 0x67]); webm.extend(vint_bytes(seg_body.len() as u64, 8).unwrap()); webm.extend(&seg_body);
        let m = mark_ai(&webm, "webm", "wan", "bears", false);
        assert!(m.len() > webm.len() && String::from_utf8_lossy(&m).contains("AI_GENERATED") && String::from_utf8_lossy(&m).contains("reportabuse"));
        let seg = webm.len() - seg_body.len();
        let (sl, _) = vint(&m, seg - 8).unwrap(); assert_eq!(seg as u64 + sl, m.len() as u64);
        let mut q = seg; let mut ids = vec![];
        while q < m.len() { let il = id_len(&m, q).unwrap(); ids.push(m[q..q + il].to_vec()); let (l, w) = vint(&m, q + il).unwrap(); q += il + w + l as usize; }
        assert_eq!(q, m.len());
        assert_eq!(ids, vec![vec![0x11, 0x4D, 0x9B, 0x74], vec![0xEC], vec![0x1F, 0x43, 0xB6, 0x75], vec![0x12, 0x54, 0xC3, 0x67]]);
        // damaged files are left alone, never a panic or a huge allocation: a Void claiming 2^40 bytes, sizes past the end
        let mut bad = webm.clone(); let v = seg + seekhead.len(); bad[v + 1] = 0x01; bad.splice(v + 2..v + 2, [0, 0, 1, 0, 0, 0, 0]);
        bad.splice(seg - 8..seg, vint_bytes(seg_body.len() as u64 + 7, 8).unwrap());  // the Segment size still matches: the Void check is reached
        assert!(webm_tags(&bad, &[("A", "b")]).map(|m| m.len() < bad.len() + 4096).unwrap_or(true));
        for cut in [5, 12, 20, webm.len() - 3] { let _ = mark_ai(&webm[..cut], "webm", "", "", false); }
        assert_eq!(mark_ai(b"\x1a\x45\xdf\xa3\x01", "webm", "", "", false), b"\x1a\x45\xdf\xa3\x01");
        // multipart: a part without headers before the next boundary is skipped (no panic); the audio part is found
        let mp = b"--X\r\nno headers here\r\n--X\r\nContent-Type: audio/mpeg\r\n\r\nSONG\r\n--X--";
        assert_eq!(audio_in_multipart(mp, "multipart/mixed; boundary=X").map(|x| x.0), Some(b"SONG".to_vec()));
        assert!(audio_in_multipart(b"--X\r\nContent-Type: audio/mpeg\r\n--X--", "multipart/mixed; boundary=X").is_none());
        // Library paths: no absolute, UNC, drive, "." or ".." paths; links out of the folder are refused
        let lib = std::env::temp_dir().join(format!("sushila-resolve-{}", std::process::id())); std::fs::create_dir_all(lib.join("images")).unwrap();
        std::fs::write(lib.join("images/a.png"), b"x").unwrap();
        assert!(resolve(&lib, "images/a.png").is_some());
        for bad in ["/etc/passwd", "\\\\host\\share\\x", "\\Users\\me", "C:\\x", "images/../images/a.png", "./images/a.png", "images//a.png", ""] { assert!(resolve(&lib, bad).is_none(), "{bad}"); }
        #[cfg(unix)] { std::os::unix::fs::symlink("/etc/hostname", lib.join("images/out.png")).unwrap(); assert!(resolve(&lib, "images/out.png").is_none()); }
        let _ = std::fs::remove_dir_all(&lib);
        // a real video (SUSHILA_WEBM_SAMPLE=<file>): writes <file>.marked.webm for ffprobe and players
        if let Ok(f) = std::env::var("SUSHILA_WEBM_SAMPLE") { let v = std::fs::read(&f).unwrap(); let m = mark_ai(&v, "webm", "wan2.2", "two bears", false); assert!(m.len() > v.len()); std::fs::write(format!("{f}.marked.webm"), m).unwrap(); }
        assert_eq!(m.len() - webm.len(), m.len() - m.windows(4).rposition(|w| w == [0x12, 0x54, 0xC3, 0x67]).unwrap());  // the Void absorbed the Seek entry
        assert_eq!(iso(std::time::UNIX_EPOCH + std::time::Duration::from_secs(1_760_000_000)), "2025-10-09T08:53:20Z");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
